language: bash

env:
  global:
  - DOCKER_IMAGE="guangie88/spark-jupyterhub"
  - FROM_DOCKER_IMAGE="guangie88/spark-k8s-addons"

matrix:
  include:
  - services: docker
    env:
    - JUPYTERHUB_VERSION=1.0.0
    - SPARK_VERSION=master-36f8e53
    - HADOOP_VERSION=3.2.0
  - services: docker
    env:
    - JUPYTERHUB_VERSION=1.0.0
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0

script:
- FROM_DOCKER_TAG=${SPARK_VERSION}_hadoop-${HADOOP_VERSION}
- PY4J_SRC=$(docker run --rm -t ${FROM_DOCKER_IMAGE}:${FROM_DOCKER_TAG} sh -c 'ls ${SPARK_HOME}/python/lib/py4j* | sed -E "s/.+(py4j-.+)/\1/" | tr -d "\n"')
- |-
  docker build . \
    --build-arg "FROM_DOCKER_IMAGE=${FROM_DOCKER_IMAGE}" \
    --build-arg "JUPYTERHUB_VERSION=${JUPYTERHUB_VERSION}" \
    --build-arg "SPARK_VERSION=${SPARK_VERSION}" \
    --build-arg "HADOOP_VERSION=${HADOOP_VERSION}" \
    --build-arg "PY4J_SRC=${PY4J_SRC}" \
    -t "${DOCKER_IMAGE}:${JUPYTERHUB_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}"

deploy:
  provider: script
  script: bash push-images.sh
  on:
    branch: master

branches:
  only:
  - master
