version: '2'
services:
  jupyterhub:
    build: .
    ports:
    - 8000:8000
    volumes:
    - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    environment:
      OAUTH_CALLBACK_URL: http://localhost:8000/hub/oauth_callback
      OAUTH_CLIENT_ID: 
      OAUTH_CLIENT_SECRET: 
