#!/usr/bin/env bash
set -euo pipefail

docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

DOCKER_TAG_NAME="${JUPYTERHUB_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}"
docker tag "${DOCKER_IMAGE}:${DOCKER_TAG_NAME}" "${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_NAME}"
docker push "${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG_NAME}"
