name: CI

on:
  push:
    branches:
    - master
    - v*
  pull_request:
    branches:
    - master
    - v*

jobs:
  build:
    strategy:
      matrix:
        version:
        - jupyterhub: "1.0"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.0"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.0"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.0"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.0"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.0"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.1"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.1"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.1"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.1"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.1"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.1"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.2"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.2"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.2"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.2"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.2"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.2"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.3"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.3"
          spark:      "2.4.5"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.3"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.3"
          spark:      "2.4.6"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.3"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.11"
        - jupyterhub: "1.3"
          spark:      "2.4.7"
          hadoop:     "3.1.0"
          scala:      "2.12"
        - jupyterhub: "1.0"
          spark:      "3.0.0"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.0"
          spark:      "3.0.1"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.1"
          spark:      "3.0.0"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.1"
          spark:      "3.0.1"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.2"
          spark:      "3.0.0"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.2"
          spark:      "3.0.1"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.3"
          spark:      "3.0.0"
          hadoop:     "3.2.0"
          scala:      "2.12"
        - jupyterhub: "1.3"
          spark:      "3.0.1"
          hadoop:     "3.2.0"
          scala:      "2.12"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: spark-jupyterhub
      SELF_VERSION: "v2"
      BASE_VERSION: "v2"
      JUPYTERHUB_VERSION: "${{ matrix.version.jupyterhub }}"
      SPARK_VERSION: "${{ matrix.version.spark }}"
      HADOOP_VERSION: "${{ matrix.version.hadoop }}"
      SCALA_VERSION: "${{ matrix.version.scala }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tera-cli
      run: |-
        wget https://github.com/guangie88/tera-cli/releases/download/v0.4.0/tera_linux_amd64 -O /tmp/tera
        chmod +x /tmp/tera
    - name: Check differences between ci.yml and ci.yml.tmpl
      run: |-
        cp .github/workflows/ci.yml .github/workflows/ci.yml.backup
        TERA=/tmp/tera ./templates/apply-vars.sh
        if ! diff .github/workflows/ci.yml .github/workflows/ci.yml.backup; then echo "ci.yml.tmpl and ci.yml differs!" && exit 1; fi
    - name: Build Docker image
      run: |-
        TAG_NAME="${SELF_VERSION}_${JUPYTERHUB_VERSION}_spark-${SPARK_VERSION}_hadoop-${HADOOP_VERSION}_scala-${SCALA_VERSION}"
        docker build . -t "${IMAGE_NAME}:${TAG_NAME}" \
          --build-arg BASE_VERSION="${BASE_VERSION}" \
          --build-arg JUPYTERHUB_VERSION="${JUPYTERHUB_VERSION}" \
          --build-arg SPARK_VERSION="${SPARK_VERSION}" \
          --build-arg HADOOP_VERSION="${HADOOP_VERSION}" \
          --build-arg SCALA_VERSION="${SCALA_VERSION}" \
    - name: Push Docker image
      run: bash push-images.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_ORG: ${{ secrets.IMAGE_ORG }}
      if: github.event_name == 'push'
